{
  "blueprint" : "testblueprint1",
  "default_password" : "BadPass#1",
  "configurations" : [
    { "ams-grafana-env" : {
      "metrics_grafana_password" : "BadPass@1"
      }
    }
  ],
  "host_groups" :[
    { "name" : "host_group_1",
      "hosts" :[ { "fqdn" : "node1"} ]
      },
    { "name" : "host_group_2",
      "hosts" :[ { "fqdn" : "node2" } ]
      },
    { "name" : "host_group_3",
      "hosts" :[ { "fqdn" : "node3" } ]
    }
  ]
}
